security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_USER:        [ ROLE_USER ]
        ROLE_ADMIN:       [ ROLE_USER, ROLE_MODERATOR, ROLE_API, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]
    providers:
        fos_userbundle:
           id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: user123, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin123, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: ROLE_ADMIN }
