<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_api_doc.controller.swagger' shared service.

include_once $this->targetDirs[3].'\\vendor\\nelmio\\api-doc-bundle\\Controller\\DocumentationController.php';

return $this->services['nelmio_api_doc.controller.swagger'] = new \Nelmio\ApiDocBundle\Controller\DocumentationController(${($_ = isset($this->services['nelmio_api_doc.generator']) ? $this->services['nelmio_api_doc.generator'] : $this->load(__DIR__.'/getNelmioApiDoc_GeneratorService.php')) && false ?: '_'});
