<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5btijj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5btijj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS5btijj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS5btijj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS5btijj\appProdProjectContainer(array(
    'container.build_hash' => 'S5btijj',
    'container.build_id' => '42294d4d',
    'container.build_time' => 1559867974,
));
