<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjpfxyi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjpfxyi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFjpfxyi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFjpfxyi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFjpfxyi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fjpfxyi',
    'container.build_id' => 'c1dfb775',
    'container.build_time' => 1559868013,
));
